[package]
name = "ownable-std"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = "1.0.0"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
serde_with = "2.0.1"
blake2 = "0.10.6"
sha2 = "0.10.6"
bs58 = "0.4.0"
secp256k1 = "0.26.0"
hex = "0.4.3"
sha3 = "0.7.2"


[dev-dependencies]